#//OpenDF :: An open source implementation of DFramework.]
#//	(C)2018 OpenDF Project
#//
#//	Read LICENSE file for licenses and copyrights information before using this file.
#//

# OpenDF Makefile for linux
#	When type 'make' in Windows: Ignore this file by default, will run 'make.cmd' instead.

# variables


# commands

:default
	@echo Unfortunately, Linux is not supported currently. 
:all

:clean

